name: spiking_simulations
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aedat=2.0.0
  - astor=0.8.1
  - audioread=3.0.0
  - blas=2.121
  - blas-devel=3.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.15.1
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - cycler=0.11.0
  - dbus=1.16.2
  - decorator=5.1.1
  - expat=2.7.1
  - ffmpeg=4.3
  - fontconfig=2.14.2
  - fonttools=4.38.0
  - freetype=2.12.1
  - gast=0.5.5
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gnutls=3.6.13
  - google-pasta=0.2.0
  - grpc-cpp=1.48.1
  - grpcio=1.48.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.7.0
  - hdf5=1.12.2
  - icu=73.2
  - idna=3.10
  - importrosbag=1.0.4
  - joblib=1.3.2
  - jpeg=9e
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - keyutils=1.6.3
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.44
  - lerc=3.0
  - libabseil=20220623.0
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdeflate=1.10
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.80.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopus=1.5.2
  - libpng=1.6.43
  - libpq=12.20
  - libprotobuf=3.21.8
  - librosa=0.10.2.post1
  - libsndfile=1.2.2
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.3.0
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libzlib=1.2.13
  - llvm-openmp=21.1.4
  - llvmlite=0.39.1
  - loris=0.5.3
  - markdown=3.6
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2024.0.0
  - mkl-devel=2024.0.0
  - mkl-include=2024.0.0
  - mpg123=1.32.9
  - msgpack-python=1.0.4
  - munkres=1.1.4
  - mysql=5.7.20
  - ncurses=6.5
  - nettle=3.6
  - numba=0.56.3
  - numpy=1.21.6
  - olefile=0.47
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.5.4
  - packaging=23.2
  - pandas=1.3.5
  - pbr=6.1.0
  - pcre2=10.43
  - pillow=8.4.0
  - pip=24.0
  - platformdirs=4.0.0
  - pooch=1.8.2
  - protobuf=4.21.8
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyparsing=3.1.4
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.7.12
  - python-dateutil=2.9.0
  - python_abi=3.7
  - pytorch=1.13.1
  - pytorch-mutex=1.0
  - pytz=2024.2
  - qt-main=5.15.2
  - re2=2022.06.01
  - readline=8.2
  - requests=2.32.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=59.8.0
  - sip=6.5.1
  - six=1.16.0
  - soxr=0.1.3
  - soxr-python=0.3.2
  - sqlite=3.46.0
  - tbb=2021.13.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=2.3.0
  - threadpoolctl=3.1.0
  - tk=8.6.13
  - toml=0.10.2
  - tonic=1.2.2
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.2
  - tqdm=4.67.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - unicodedata2=14.0.0
  - urllib3=2.2.1
  - werkzeug=2.2.3
  - wheel=0.42.0
  - wrapt=1.14.1
  - xkeyboard-config=2.46
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - importlib-metadata==6.7.0
      - nir==1.0.1
      - nirtorch==2.0.2
      - snntorch==0.8.0
prefix: /home/mark/anaconda3/envs/spiking_simulations
