name: whk-snn
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.1.31
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cpython=3.9.21
  - cycler=0.12.1
  - debugpy=1.8.13
  - decorator=5.2.1
  - deprecated=1.2.13
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.18.0
  - fonttools=4.57.0
  - freetype=2.13.3
  - fsspec=2025.3.2
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h5py=3.9.0
  - hdf5=1.14.1
  - icu=70.1
  - importlib-metadata=8.5.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=8.1.2
  - libdeflate=1.22
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.78.4
  - libgomp=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libogg=1.3.5
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libuv=1.50.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nir=1.0.4
  - nirtorch=2.0.2
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.1
  - opentelemetry-api=1.30.0
  - optree=0.14.1
  - packaging=24.2
  - pandas=1.4.4
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - platformdirs=4.3.7
  - ply=3.11
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytorch=2.3.1
  - pytz=2024.1
  - pywin32=307
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt-main=5.15.8
  - seaborn=0.13.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.17.0
  - sleef=3.8
  - snntorch=0.9.4
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.13.3
  - tbb=2021.13.0
  - tk=8.6.13
  - tomli=2.0.1
  - torchvision=0.18.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.13.0
  - typing_extensions=4.13.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
prefix: C:\Users\Mark\miniconda3\envs\whk-snn
