name: whk-snn
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - bottleneck=1.4.2=py39hc99e966_0
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.2.25=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h2b77a98_2
  - cpython=3.9.21=py39hd8ed1ab_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.13=py39ha51f57c_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.2.13=py39haa95532_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - filelock=3.18.0=pyhd8ed1ab_0
  - fonttools=4.57.0=py39hf73967f_0
  - freetype=2.13.3=h0620614_0
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - h5py=3.9.0=nompi_py39hde1a6dc_101
  - hdf5=1.14.1=nompi_h73e8ff5_100
  - icu=70.1=h0e60522_0
  - importlib-metadata=8.5.0=py39haa95532_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.18.1=pyh7428d3b_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h827c3e9_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.16=hb4a4139_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240116.2=cxx17_h5da7b33_0
  - libaec=1.1.3=h63175ca_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libblas=3.9.0=20_win64_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=20_win64_mkl
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libcurl=8.1.2=h68f0423_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.6=h537db12_1
  - libgcc=14.2.0=h1383e82_2
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.78.4=ha17d25a_0
  - libgomp=14.2.0=h1383e82_2
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblapack=3.9.0=20_win64_mkl
  - liblzma=5.6.4=h2466b09_0
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=4.25.3=hf2fb9eb_0
  - libsodium=1.0.18=h62dcd97_0
  - libsqlite=3.49.1=h67fdade_2
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.5.1=h44ae7cf_1
  - libtorch=2.5.1=cpu_mkl_h1aab2ed_102
  - libuv=1.50.0=h2466b09_0
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.3.2=h3d04722_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.5=h24da03e_0
  - libzlib=1.2.13=h2466b09_6
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py39hf73967f_1
  - matplotlib=2.2.5=h57928b3_3
  - matplotlib-base=2.2.5=py39h3fc0fd0_3
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.2.0=h6a75c08_50497
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=py39haa95532_0
  - nir=1.0.4=pyhd8ed1ab_1
  - nirtorch=2.0.2=pyhd8ed1ab_0
  - numexpr=2.10.1=py39h4cd664f_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.4.1=ha4e3fda_0
  - opentelemetry-api=1.30.0=py39haa95532_0
  - optree=0.14.1=py39h2b77a98_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=1.4.4=py39hd77b12b_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py39h096bfcc_0
  - pip=25.0.1=pyh8b19718_0
  - platformdirs=4.3.7=pyh29332c3_0
  - ply=3.11=py39haa95532_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=7.0.0=py39ha55e580_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyhab904b8_2
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.10=py39h5da7b33_1
  - pyqt5-sip=12.13.0=py39h827c3e9_1
  - python=3.9.21=h8205438_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=2.3.1=cpu_py39h0ce1571_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=307=py39ha51f57c_3
  - pyzmq=26.2.0=py39h5da7b33_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.8=h720456b_6
  - setuptools=72.1.0=py39haa95532_0
  - sip=6.7.12=py39h5da7b33_1
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h7e360cc_0
  - snntorch=0.9.4=pyhd8ed1ab_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.13.3=pyh04b8f61_5
  - tbb=2021.13.0=h62715c5_1
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=py39haa95532_0
  - torchvision=0.18.1=cpu_py39h9788fc5_0
  - tornado=6.4.2=py39h827c3e9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.13.0=h9fa5a19_1
  - typing_extensions=4.13.0=pyh29332c3_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py39ha55e580_0
  - vc=14.42=haa95532_4
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.0=py39h827c3e9_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.6=h8880b57_0
prefix: C:\Users\Mark\miniconda3\envs\whk-snn
