name: spiking_simulations
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - h5py=3.7.0
  - hdf5=1.12.2
  - matplotlib=3.5.3
  - numpy=1.21.6
  - pandas=1.3.5
  - pip=24.0
  - python=3.7.12
  - pytorch=1.13.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - tensorflow=1.14.0
  - tonic=1.2.2
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - pip:
      - importlib-metadata==6.7.0
      - nir==1.0.1
      - nirtorch==2.0.2
      - snntorch==0.8.0
